### ISSUE TITLE
Leaf storm increasing sp atk - Courtney Magma Admin

### ISSUE THREAD

**Issue by GingerBumbleBee** [iriv24/pokeemerald-expansion#5]
### Description

When going through the Magma base, you run into Courtney and another magma admin. Courtney has a Serperior that knows Leaf Storm. When it uses this move, it’s sp atk stat goes up instead of down. I’ve used Leaf Storm many times on my grass cat (starter)and it always lowered the sp atk. 

### Version

beta

**Comment by GingerBumbleBee** [comment]
![IMG_3958](https://github.com/user-attachments/assets/ee8255c6-20a2-47eb-a8d7-973420f96219)
![IMG_3960](https://github.com/user-attachments/assets/856c6db0-c0e1-484a-84f3-e23f498ef607)

**Comment by iriv24** [comment]
This one is intentional and is also how Serperior works in the real games! Serperior gets the ability Contrary, which reverses the effects of stat changing moves. So for example, if Serperior had Contrary and used the move Swords Dance, his Attack would _drop_ by 2 stages instead of increasing. Similar situation here, normally you are correct that Leaf Storm drops Special Attack, but Serperior having Contrary means it _raises_ its Special Attack. It's a very strong combo haha but it's actually one that exists in normal Pokemon games and isn't something I added :D

![image](https://github.com/user-attachments/assets/866b4df0-c425-483e-8010-0ff7ef3ef21c)

**Comment by iriv24** [comment]
Also i really appreciate the screenshots!! this is like the best case scenario for me to investigate issues from, super helpful so thank you very very much!
